=== UO270656/SEW/practica2/ejercicio2/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta  (fecha_ini, hora_ini, duracion, agencia, descripcion, target, lugar_ini, direccion_ini, long_ini, lat_ini, alt_ini, referencias, recomendacion, hitos)>
<!ELEMENT fecha_ini (#PCDATA)>
<!ELEMENT hora_ini (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT target (#PCDATA)>
<!ELEMENT lugar_ini (#PCDATA)>
<!ELEMENT direccion_ini (#PCDATA)>
<!ELEMENT long_ini (#PCDATA)>
<!ELEMENT lat_ini (#PCDATA)>
<!ELEMENT alt_ini (#PCDATA)>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>
<!ELEMENT hitos (hito+)>
<!ELEMENT hito (descripcion, long_hito, lat_hito, alt_hito, distancia_h_anterior, tiempo_h_anterior, fotografias, videos)>
<!ELEMENT long_hito (#PCDATA)>
<!ELEMENT lat_hito (#PCDATA)>
<!ELEMENT alt_hito (#PCDATA)>
<!ELEMENT distancia_h_anterior (#PCDATA)>
<!ELEMENT tiempo_h_anterior (#PCDATA)>
<!ELEMENT fotografias (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT videos (video+)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST ruta nombre CDATA #REQUIRED>
<!ATTLIST ruta tipo CDATA #REQUIRED>
<!ATTLIST ruta dificultad CDATA #REQUIRED>
<!ATTLIST fecha_ini formato CDATA #REQUIRED>
<!ATTLIST hora_ini indicador CDATA #REQUIRED>
<!ATTLIST duracion unidad CDATA #REQUIRED>
<!ATTLIST alt_ini unidad CDATA #REQUIRED>
<!ATTLIST hito nombre CDATA #REQUIRED>
<!ATTLIST alt_hito unidades CDATA #REQUIRED>
<!ATTLIST distancia_h_anterior unidades CDATA #REQUIRED>
<!ATTLIST tiempo_h_anterior unidades CDATA #REQUIRED>

=== UO270656/SEW/practica2/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas>
  <ruta nombre="Ruta del miedevo" tipo="Arquitectura y monumentos" dificultad="alta">
    <fecha_ini formato="DD/MM/AAAA">28/10/2020</fecha_ini>
    <hora_ini indicador="AM">09:00</hora_ini>
    <duracion unidad="minutos">78</duracion>
    <agencia>Dronsturias</agencia>
    <descripcion>Esta ruta te permite ver todos los monumentos de la capital en un trazado sinuoso entre los edificios mas característicos de Oviedo</descripcion>
    <target>Apto solo para publico experimentado en el manejo de drones</target>
    <lugar_ini>Oviedo</lugar_ini>
    <direccion_ini>Plaza Alfonso II el Casto, s/n, 33003 Oviedo, Asturias</direccion_ini>
    <long_ini>43.362287</long_ini>
    <lat_ini>-5.844144</lat_ini>
    <alt_ini unidad="metros">230</alt_ini>
    <referencias>
      <referencia>https://es.wikipedia.org/wiki/Monumentos_de_Oviedo_y_del_Reino_de_Asturias</referencia>
      <referencia>http://el.tesorodeoviedo.es/index.php?title=Plaza_del_Paraguas</referencia>
      <referencia>https://buendiatours.com/es/guias/oviedo/monumentos-principales</referencia>
    </referencias>
    <recomendacion>7</recomendacion>
    <hitos>
      <hito nombre="Foncalada">
        <descripcion>La Foncalada” de Oviedo , está considerada como el monumento civil en uso continuado más antiguo de España, 
        pues hasta principios del Siglo XX, aún era utilizada por las mujeres como lavadero.Fué declarado como Patrimonio de la Humanidad por la UNESCO en el año 1985.
        </descripcion>
        <long_hito>43.365253</long_hito>
        <lat_hito>-5.846022</lat_hito>
        <alt_hito unidades="metros">200</alt_hito>
        <distancia_h_anterior unidades="metros">350</distancia_h_anterior>
        <tiempo_h_anterior unidades="minutos">10</tiempo_h_anterior>
        <fotografias>
          <foto></foto>
          <foto></foto>
          <foto></foto>
          <foto></foto>
          <foto></foto>
        </fotografias>
        <videos>
          <video></video>
          <video></video>
          <video></video>
        </videos>
      </hito>
      <hito nombre="La Plaza de la Escandalera">
        <descripcion>La Plaza de la Escandalera es sin duda, la plaza más conocida de Oviedo. En ella los mayores descansan al sol en sus bancos, 
        es punto de encuentro para jóvenes, y lugar de paso para todos los ovetenses. Enlaza la zona comercial, el casco antiguo y el centro político de la ciudad.
        </descripcion>
        <long_hito>43.365253</long_hito>
        <lat_hito>-5.846022</lat_hito>
        <alt_hito unidades="metros">225</alt_hito>
        <distancia_h_anterior unidades="metros">390</distancia_h_anterior>
        <tiempo_h_anterior unidades="minutos">13</tiempo_h_anterior>
        <fotografias>
          <foto></foto>
          <foto></foto>
          <foto></foto>
          <foto></foto>
          <foto></foto>
        </fotografias>
        <videos>
          <video></video>
          <video></video>
          <video></video>
        </videos>
      </hito>
      <hito nombre="Plaza del Paraguas">
        <descripcion>
          Plaza ovetense que se ubica en la calle de San Isidoro puesto que se levantó en el lugar donde se encontraba la antigua iglesia románica de San Isidoro, 
          demolida en el año 1922. Se proyectó entonces un mercado para la venta de leche que, anteriormente, se realizaba en la Plaza Trascorrales.
        </descripcion>
        <long_hito>43.360783</long_hito>
        <lat_hito>-5.842723</lat_hito>
        <alt_hito unidades="metros">227</alt_hito>
        <distancia_h_anterior unidades="metros">440</distancia_h_anterior>
        <tiempo_h_anterior unidades="minutos">13</tiempo_h_anterior>
        <fotografias>
          <foto></foto>
          <foto></foto>
          <foto></foto>
          <foto></foto>
          <foto></foto>
        </fotografias>
        <videos>
          <video></video>
          <video></video>
          <video></video>
        </videos>
      </hito>
    </hitos>
  </ruta>
  <ruta nombre="Ruta de las cascadas de Oneta" tipo="Naturaleza" dificultad="media">
    <fecha_ini formato="DD/MM/AAAA">01/11/2020</fecha_ini>
    <hora_ini indicador="AM">12:00</hora_ini>
    <duracion unidad="minutos">96</duracion>
    <agencia>Asturias Impulsa</agencia>
    <descripcion>Esta ruta te permite contemplar la majestuosidad de las cascadas de Oneta sin realizar un esfuerzo físico</descripcion>
    <target>Apto para todo el público</target>
    <lugar_ini>Oneta</lugar_ini>
    <direccion_ini>33717 Oneta, Asturias</direccion_ini>
    <long_ini>43.464266</long_ini>
    <lat_ini>-6.667482</lat_ini>
    <alt_ini unidad="metros">313</alt_ini>
    <referencias>
      <referencia>https://guiadeasturias.com/lugar/ruta-las-cascadas-oneta-una-dos-tres-los-saltos-agua-disfrutaremos-este-recorrido/</referencia>
      <referencia>https://www.turismoasturias.es/descubre/naturaleza/rutas/senderismo/cascadas-de-oneta</referencia>
      <referencia>https://lasendadelhayedo.com/cascadas-de-oneta/</referencia>
    </referencias>
    <recomendacion>9</recomendacion>
    <hitos>
      <hito nombre="Ermita de Santa María de Oneta">
        <descripcion>
          Ermita de Santa María localizada en Oneta, la localidad donde da comienzo la ruta.
        </descripcion>
        <long_hito>43.464957</long_hito>
        <lat_hito>-6.666817</lat_hito>
        <alt_hito unidades="metros">310</alt_hito>
        <distancia_h_anterior unidades="metros">100</distancia_h_anterior>
        <tiempo_h_anterior unidades="minutos">3</tiempo_h_anterior>
        <fotografias>
          <foto></foto>
          <foto></foto>
          <foto></foto>
          <foto></foto>
          <foto></foto>
        </fotografias>
        <videos>
          <video></video>
          <video></video>
          <video></video>
        </videos>
      </hito>
      <hito nombre="Cascadas de Oneta">
        <descripcion>
          El agua, fuente de vida, nos llama poderosamente la atención, nos atrae, y más cuando por la climatología o por la orografí­a nos 
          muestra toda su fuerza y poder y se convierte en belleza. Esto es lo que nos enseñan las cascadas de Oneta, al menos dos de las tres existentes.
        </descripcion>
        <long_hito>43.460483</long_hito>
        <lat_hito>-6.675045</lat_hito>
        <alt_hito unidades="metros">260</alt_hito>
        <distancia_h_anterior unidades="metros">820</distancia_h_anterior>
        <tiempo_h_anterior unidades="minutos">26</tiempo_h_anterior>
        <fotografias>
          <foto></foto>
          <foto></foto>
          <foto></foto>
          <foto></foto>
          <foto></foto>
        </fotografias>
        <videos>
          <video></video>
          <video></video>
          <video></video>
        </videos>
      </hito>
      <hito nombre="Molinos de Oneta">
        <descripcion>
          Molinos de agua que aprovechan la fuerza del agua de las cascadas de Oneta
        </descripcion>
        <long_hito>43.459942</long_hito>
        <lat_hito>-6.675580</lat_hito>
        <alt_hito unidades="metros">250</alt_hito>
        <distancia_h_anterior unidades="metros">75</distancia_h_anterior>
        <tiempo_h_anterior unidades="minutos">2</tiempo_h_anterior>
        <fotografias>
          <foto></foto>
          <foto></foto>
          <foto></foto>
          <foto></foto>
          <foto></foto>
        </fotografias>
        <videos>
          <video></video>
          <video></video>
          <video></video>
        </videos>
      </hito>
    </hitos>
  </ruta>
  <ruta nombre="La costa de los dinosaurios" tipo="Didáctica" dificultad="baja">
    <fecha_ini formato="DD/MM/AAAA">31/10/2020</fecha_ini>
    <hora_ini indicador="PM">6:00</hora_ini>
    <duracion unidad="minutos">125</duracion>
    <agencia>Dronsturias</agencia>
    <descripcion>En esta ruta visitaremos el Museo Jurásico de Asturias y deferentes puntos en la costa asturiana donde podremos observar huellas prehistóricas de dinosaurio
    </descripcion>
    <target>Muy recomendado para niños</target>
    <lugar_ini>Colunga</lugar_ini>
    <direccion_ini>Rasa de San Telmo, s/n, 33328 Colunga, Asturias</direccion_ini>
    <long_ini>43.500924</long_ini>
    <lat_ini>-5.274223</lat_ini>
    <alt_ini unidad="metros">150</alt_ini>
    <referencias>
      <referencia>https://guiadeasturias.com/lugar/la-costa-los-dinosaurios/</referencia>
      <referencia>http://www.museojurasicoasturias.com/</referencia>
      <referencia>http://www.museojurasicoasturias.com/es/9/la-costa-de-los-dinosaurios/12/la-costa-de-los-dinosaurios/13/playa-de-la-griega.html</referencia>
    </referencias>
    <recomendacion>6</recomendacion>
    <hitos>
      <hito nombre="MUJA">
        <descripcion>
          El Museo del Jurásico de Asturias (MUJA) es un pequeño museo paleontólogico español que se encuentra aislado en la rasa costera de San Telmo, 
          entre las localidades asturianas de Colunga y Lastres, donde se han encontrado vestigios de dinosaurios que habrían poblado la región hace unos 
          150 millones de años, durante la última parte del Jurásico.
        </descripcion>
        <long_hito>43.500924</long_hito>
        <lat_hito>-5.274223</lat_hito>
        <alt_hito unidades="metros">150</alt_hito>
        <distancia_h_anterior unidades="metros">0</distancia_h_anterior>
        <tiempo_h_anterior unidades="minutos">0</tiempo_h_anterior>
        <fotografias>
          <foto></foto>
          <foto></foto>
          <foto></foto>
          <foto></foto>
          <foto></foto>
        </fotografias>
        <videos>
          <video></video>
          <video></video>
          <video></video>
        </videos>
      </hito>
      <hito nombre="La playa de la Griega">
        <descripcion>
